// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAllRiskAssessments():Promise<Array<models.RiskAssessment>>;

export function GetAllStockRatings():Promise<Array<models.StockRating>>;

export function GetAllTrades():Promise<Array<models.Trade>>;

export function GetLatestRiskAssessment():Promise<models.RiskAssessment>;

export function GetStockRating(arg1:number):Promise<models.StockRating>;

export function GetStockRatingsByTicker(arg1:string):Promise<Array<models.StockRating>>;

export function GetTrade(arg1:number):Promise<models.Trade>;

export function GetTradesByDateRange(arg1:string,arg2:string):Promise<Array<models.Trade>>;

export function GetTradesByTicker(arg1:string):Promise<Array<models.Trade>>;

export function GetVersion():Promise<string>;

export function SaveRiskAssessment(arg1:models.RiskAssessment):Promise<models.RiskAssessment>;

export function SaveStockRating(arg1:models.StockRating):Promise<models.StockRating>;

export function SaveTrade(arg1:models.Trade):Promise<models.Trade>;
