// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRiskAssessments() {
  return window['go']['main']['App']['GetAllRiskAssessments']();
}

export function GetAllStockRatings() {
  return window['go']['main']['App']['GetAllStockRatings']();
}

export function GetAllTrades() {
  return window['go']['main']['App']['GetAllTrades']();
}

export function GetLatestRiskAssessment() {
  return window['go']['main']['App']['GetLatestRiskAssessment']();
}

export function GetStockRating(arg1) {
  return window['go']['main']['App']['GetStockRating'](arg1);
}

export function GetStockRatingsByTicker(arg1) {
  return window['go']['main']['App']['GetStockRatingsByTicker'](arg1);
}

export function GetTrade(arg1) {
  return window['go']['main']['App']['GetTrade'](arg1);
}

export function GetTradesByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetTradesByDateRange'](arg1, arg2);
}

export function GetTradesByTicker(arg1) {
  return window['go']['main']['App']['GetTradesByTicker'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveRiskAssessment(arg1) {
  return window['go']['main']['App']['SaveRiskAssessment'](arg1);
}

export function SaveStockRating(arg1) {
  return window['go']['main']['App']['SaveStockRating'](arg1);
}

export function SaveTrade(arg1) {
  return window['go']['main']['App']['SaveTrade'](arg1);
}
